---
title: "Exploring Gapminder Data"
author: "Gokul Raj Suresh Kumar"
date: "`r format(Sys.Date())`"
output: github_document
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE)
```

## Loading the Gapminder data

```{r}
library("gapminder")
gapminder
```

## Summarizing the Gapminder data

```{r}
summary(gapminder)
```

## Observations associated with each continent

```{r}
barplot(table(gapminder$continent))
```

## Life Expectancy vs GDP per capita 

```{r}
plot(lifeExp ~ log(gdpPercap), gapminder)
```

## Life Expectancy vs GDP per capita - Segregated View

```{r}
library(ggplot2)
p <- ggplot(subset(gapminder),
            aes(x = gdpPercap, y = lifeExp)) 
p <- p + scale_x_log10()
p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) + 
geom_smooth(lwd = 1.5, se = FALSE)
```

## Frequency of occurence of Life Expectancy 

```{r}
hist(gapminder$lifeExp)
```

## Life Expectancy vs Year for India

```{r}
p <- ggplot(subset(gapminder, country == "India"),
           aes(x = year, y = lifeExp)) 
p + geom_point() + geom_smooth(lwd = 1.5, se = FALSE, method = "lm")
```

## Correlation of Life Expectancy and GDP per capita for India

```{r}
with(subset(gapminder, subset = country == "India"),
       cor(lifeExp, gdpPercap))
```
