---
title: "Gapminder, ggplot2 and dplyr single table verbs"
author: "Gokul Raj Suresh Kumar"
date: "`r format(Sys.Date())`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Manipulate and Explore Gapminder with dplyr & ggplot2

####Loading the tidyverse and gapminder packages 

```{r message=FALSE}
library( tidyverse )
library( gapminder )
```

##Tasks

####Maximum and Minimum of `gdpPercap` for all continents

```{r results = 'asis'}
my_gap <- gapminder

min_max_gdp <- my_gap %>% 
  group_by( continent ) %>% 
  summarize( min_gdp_percap = min( gdpPercap ) , max_gdp_percap = max( gdpPercap ))

knitr::kable( min_max_gdp )
```

```{r}
min_max_gdp %>% 
  ggplot(aes( x = continent , y = min_gdp_percap )) +
  geom_bar( width = 0.10 , stat = "identity")

min_max_gdp %>% 
  ggplot(aes( x = continent , y = max_gdp_percap )) +
  geom_bar( width = 0.10 , stat = "identity")
```

####Weighted Mean of `lifeExp` (by population) 

```{r}
le_wt_mean <- my_gap %>% 
  group_by( continent ) %>% 
  summarize( mean_wt_le = weighted.mean( lifeExp, pop )) %>% 
  print(n = Inf)
```

```{r}
le_wt_mean %>% 
  ggplot(aes( x = continent , y = mean_wt_le)) +
  geom_bar( width = 0.10 , stat = "identity")
```

####`lifeExp` over time for different continents

```{r}
le_over_time <- my_gap %>%
  select( continent , lifeExp , year ) %>%
  group_by( continent , year ) %>% 
  summarise( avg_life_exp = mean( lifeExp )) %>% 
  print( n = 10 )
```

```{r}
le_over_time %>%
  ggplot( aes( x = year , y = avg_life_exp )) + 
  geom_point( aes( color = continent )) + 
  geom_line( aes( group = continent , color =   continent ))
```

####Relative abundance of countries with low life expectancy over time by continent

```{r}
benchmark_country <- my_gap %>% 
  filter( country == "India" )

rel_le <- my_gap %>% 
  mutate( temp = rep( benchmark_country$lifeExp , nlevels( country )), 
          lifeExpRel = lifeExp/temp, 
          temp = NULL)

rel_abundance <- rel_le %>%
  group_by( continent , year)%>% 
  filter( lifeExpRel < 1 )%>% 
  summarise( n_countries = n_distinct( country )) %>% 
  print( n = 10 )
```

```{r}
rel_abundance %>%
  ggplot( aes( x = year , y = n_countries , fill = continent )) + 
  geom_bar( stat = "identity" , position = "stack")
```




