---
title: "Factor and Figure Management"
author: "Gokul Raj Suresh Kumar"
date: "`r format(Sys.Date())`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Factor and Figure Management

####Loading the required packages

```{r message=FALSE}
library(gapminder)
library(tidyverse)
library(forcats)
```

##Factor Management

###Dropping Oceania

####Gapminder's details

```{r}
gapminder %>% 
  count( continent )
nrow( gapminder )
nlevels( gapminder$continent )
nlevels( gapminder$country )
```

####Oceania's details 

```{r}
just_oceania <- gapminder %>%
  filter( continent == "Oceania" ) %>%
  droplevels()
just_oceania %>%
  count( continent )
nrow( just_oceania )
nlevels( just_oceania$continent )
nlevels( just_oceania$country )
```

####Details after dropping Oceania

```{r}
# Dropping Oceania and it's factor levels
(without_oceania <- gapminder %>%
  filter( continent != "Oceania" ) %>%
  droplevels())
# The tibble shows that Oceania has been removed
without_oceania %>%
  count( continent )
# 1704 - 24 (All continents - Oceania)
nrow( without_oceania )
# 5 - 1 (All continents - Oceania)
nlevels( without_oceania$continent )
# 142 - 2 (All countries - (New Zealand + Australia))
nlevels( without_oceania$country )
```

###Reordering the levels of `country` 
